// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Envelopes
	{

		public static float[] sharpAttackEnvelope = new float[32]{	0.2f,
																	0.4f,
																	0.6f,
																	0.8f,
																	1f,
																	0.95f,
																	0.9f,
																	0.85f,
																	0.8f,
																	0.75f,
																	0.7f,
																	0.65f,
																	0.6f,
																	0.55f,
																	0.5f,
																	0.45f,
																	0.4f,
																	0.35f,
																	0.3f,
																	0.25f,
																	0.2f,
																	0.15f,
																	0.1f,
																	0.05f,
																	0f,
																	0f,
																	0f,
																	0f,
																	0f,
																	0f,
																	0f,
																	0f	
																};


		public static float[] upAndDownEnvelope;

		




		public Envelopes ()
		{
			upAndDownEnvelope = new float[32];
			for (int i  = 0; i< 16; i++) 
			{
				upAndDownEnvelope[i] = (float)2f*i/31f;
			}
			for (int i  = 31; i >= 16; i--) 
			{
				upAndDownEnvelope[i] = (float)2f*(32 - i - 1)/31f;
			}

		}






	}
}

