// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum EventKind { start, appears, disappears, moves, invalid};
	public enum ObjectKind { sphere, cube, beacon};
	public struct EventDescriptor
	{
		public float eventTime;
		public ObjectKind objectKind;
		public EventKind eventKind;

	}
}

