// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace AssemblyCSharp
{
	public class Figure
	{
		public List<Vector3> points = new List<Vector3>();
		public Figure ()
		{
		}
		public void AddPoint(Vector3 point)
		{
			points.Add(point);
		}
		public int NumberOfPoints()
		{
			return points.Count;
		}
		public Vector3 getPoint(int index)
		{
			return points[index];
		}
		public void TransformCoordinates()
		{
			//TODO fill
			foreach (Vector3 point in points) 
			{
				;
			}
			
		}
	}
}

