// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


	namespace AssemblyCSharp
{
	public class SingleTimeLine
	{

		//private EventDescriptor[] events;
		private List<EventDescriptor> events = new List<EventDescriptor> ();

		private int numberOfEvents;
		private int nextEvent;

		private GameObject[] objectReferences;

		public SingleTimeLine ()
		{
			nextEvent = 0;
		}

		public SingleTimeLine(GameObject[] objectRefs){
			objectReferences = objectRefs;
			nextEvent = 0;
		}


		public float getEventTime(int eventIndex)
		{
			if (0 <= eventIndex && eventIndex < numberOfEvents)
				return events [eventIndex].eventTime;
			else
				return -1; //error

		}

		public EventKind getEventKind(int eventIndex)
		{
			if (0 <= eventIndex && eventIndex < numberOfEvents)
				return events [eventIndex].eventKind;
			else
				return EventKind.invalid; //error
			
		}


		public int getNumberOfEvents()
		{
			return numberOfEvents;
		}


		public void addEvent(EventDescriptor ev){
			events.Add (ev);
		}

		public void updateNextEvent(){
			nextEvent++;
		}
		
		public float getNextEventTime()
		{
			return events [nextEvent].eventTime;
		}
		public EventKind getNextAction()
		{
			return events [nextEvent].eventKind;
			
		}
		
		public GameObject[] getObjectReferences()
		{
			return objectReferences;
		}


	}
}

