// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class TimeLine
	{

		private EventDescriptor[] events;
		private int numberOfEvents;

		public TimeLine ()
		{
			numberOfEvents = 3;
			events = new EventDescriptor[numberOfEvents];

			events [0].eventTime = 0.0f; //event "zero" is by default the simulation start
			events [0].eventKind = EventKind.start;

			events [1].eventTime = 4.0f; //first event - object appears
			events [1].eventKind = EventKind.appears;

			events [2].eventTime = 10.0f; //second event - object disappears
			events [2].eventKind = EventKind.disappears;
			


		}
		public float getEventTime(int eventIndex)
		{
			if (0 <= eventIndex && eventIndex < numberOfEvents)
				return events [eventIndex].eventTime;
			else
				return -1; //error

		}

		public EventKind getEventKind(int eventIndex)
		{
			if (0 <= eventIndex && eventIndex < numberOfEvents)
				return events [eventIndex].eventKind;
			else
				return EventKind.invalid; //error
			
		}


		public int getNumberOfEvents()
		{
			return numberOfEvents;
		}


	}
}

